const defaultFamily=[
  {id:'mommy',dbId:'mommy',name:'Mommy',role:'Parent',buddy:'🐼',color:'#dff4ed',dateOfBirth:'',sex:'',records:0,glucose:null,status:'Waiting'},
  {id:'daddy',dbId:'daddy',name:'Daddy',role:'Parent',buddy:'🐻',color:'#fff0dc',dateOfBirth:'',sex:'',records:0,glucose:null,status:'Waiting'},
  {id:'qaayed',dbId:'qaayed',name:'Qaayed',role:'Child',buddy:'🐨',color:'#e9e6ff',dateOfBirth:'',sex:'',records:0,glucose:null,status:'Waiting'},
  {id:'qarizh',dbId:'qarizh',name:'Qarizh',role:'Child',buddy:'🐱',color:'#fde8ef',dateOfBirth:'',sex:'',records:0,glucose:null,status:'Waiting'}
];
let family = defaultFamily.map(member=>({...member}));
let healthRecords = [];
let appointments = [];
const appointmentIcons = {Dentist:'🦷','Eye Check':'👁','Doctor':'🩺',Vaccination:'💉',Specialist:'🩻','Lab / Test':'🧪',Hospital:'🏥',Other:'📅'};
// Paste your private Google Apps Script Web App URL here after deployment.
const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbyq4zQ-RSk5fHUpXMZ7dhpr7iz4H7YnFA8BgEKu0SjXUkNLHb1_S55JZNgrli_NTnLw/exec';
const labels = { glucose:['Glucose','mmol/L','e.g. 5.4'], bloodPressure:['Blood pressure','mmHg','e.g. 118/76'], pulse:['Pulse','bpm','e.g. 72'], temperature:['Temperature','°C','e.g. 36.8'], weight:['Weight','kg','e.g. 52.5'], height:['Height','cm','e.g. 165'] };
// Centralized Health Reference Engine. This provides reference status, never a diagnosis.
const healthReferenceConfig = {
  glucoseIndicator: [
    { key:'low', label:'Low', max:3.9, color:'#dc8e84' }, { key:'normal', label:'Normal', min:4.0, max:7.0, color:'#72afd0' },
    { key:'borderline', label:'Borderline', min:7.1, max:10.0, color:'#5da89e' }, { key:'high', label:'High', min:10.1, max:13.8, color:'#70859d' },
    { key:'dangerous', label:'Dangerous', min:13.9, color:'#d6b847' }
  ],
  adult: { bp: { normal:[120,80], elevated:[130,80], stage1:[140,90], severe:[180,120] }, bmi:[18.5,25,30,35,40], temperature:{typical:[36.1,37.2], fever:38}, pulse:{typical:[60,100]} },
  pediatric: { bp:{source:'AAP pediatric BP reference',requires:['age','sex','height']}, bmi:{source:'WHO growth reference',requires:['age','sex']}, pulse:{source:'Age-specific pediatric resting reference',requires:['age']} },
  source: 'Glucose Indicator Card supplied by family; AHA/ACC 2025; AAP pediatric BP reference; WHO growth references; MedlinePlus temperature guidance.'
};
function ageYears(dateOfBirth) { if(!dateOfBirth) return null; const dob=new Date(dateOfBirth); const now=new Date(); let age=now.getFullYear()-dob.getFullYear(); if(now < new Date(now.getFullYear(),dob.getMonth(),dob.getDate())) age--; return age; }
function ageGroup(dateOfBirth) { const age=ageYears(dateOfBirth); return age===null?'Unknown':age<1?'Infant':age<13?'Child':age<18?'Adolescent':'Adult'; }
function getGlucoseReference(glucose) { const value=Number(glucose); if(!Number.isFinite(value)) return null; return healthReferenceConfig.glucoseIndicator.find(t=>(t.min===undefined||value>=t.min)&&(t.max===undefined||value<=t.max)); }
function getHealthReference({dateOfBirth,sex,heightCm,weightKg,systolicBp,diastolicBp,pulseBpm,temperatureC}) { const group=ageGroup(dateOfBirth); const result={ageGroup:group,warnings:[],referenceSource:healthReferenceConfig.source}; if(heightCm&&weightKg){result.bmi=Number(weightKg)/Math.pow(Number(heightCm)/100,2); if(group==='Adult'){const b=healthReferenceConfig.adult.bmi;result.bmiCategory=result.bmi<b[0]?'Underweight range':result.bmi<b[1]?'Healthy weight range':result.bmi<b[2]?'Overweight range':result.bmi<b[3]?'Obesity class 1 range':result.bmi<b[4]?'Obesity class 2 range':'Obesity class 3 range';}else result.bmiCategory='Age- and sex-specific growth reference required';} if(systolicBp&&diastolicBp){if(group==='Adult'||group==='Adolescent'){const c=healthReferenceConfig.adult.bp;result.bpCategory=systolicBp>c.severe[0]||diastolicBp>c.severe[1]?'Severe / urgent review flag':systolicBp>=c.stage1[0]||diastolicBp>=c.stage1[1]?'Stage 2 range - repeat measurement and consider professional review':systolicBp>=c.elevated[0]||diastolicBp>=c.elevated[1]?'Stage 1 range - repeat measurement and consider professional review':systolicBp>=c.normal[0]&&diastolicBp<c.normal[1]?'Elevated range':'Within adult reference range';}else result.bpCategory=group==='Infant'?'Infant BP requires age-specific clinical reference.':'Age/sex/height-specific pediatric BP reference required';} if(temperatureC){const t=healthReferenceConfig.adult.temperature;result.temperatureCategory=temperatureC>=t.fever?'Fever reference flag':temperatureC>t.typical[1]?'Above typical range':'Typical range';} if(pulseBpm) result.pulseCategory=group==='Adult'? (pulseBpm>=60&&pulseBpm<=100?'Typical resting reference':'Outside typical resting reference - context matters'):'Age-specific pediatric reference required'; return result; }
let selectedMember = 'mommy', selectedSession = 'Before breakfast', selectedRange = 'week';

const memberAliases={mama:'mommy',mommy:'mommy',mummy:'mommy',papa:'daddy',daddy:'daddy',aisha:'qaayed',qaayed:'qaayed',adam:'qarizh',qarizh:'qarizh'};
const buddyIcons={bear:'🐻',panda:'🐼',cat:'🐱',koala:'🐨',rabbit:'🐰',capybara:'🦫',fox:'🦊'};
const buddyColours=['#dff4ed','#fff0dc','#e9e6ff','#fde8ef'];
function memberKey(value){return memberAliases[String(value||'').trim().toLowerCase()]||String(value||'').trim().toLowerCase();}
function normaliseProfile(row,index){const base=defaultFamily.find(member=>member.id===memberKey(row['Member ID']))||defaultFamily[index]||{};const animal=String(row['Buddy animal']||base.buddy||'🐾');return {...base,id:memberKey(row['Member ID']),dbId:row['Member ID'],name:base.name||row.Name||row['Member ID'],role:row.Relationship||base.role||'Family member',buddy:buddyIcons[animal.toLowerCase()]||animal.split(' ')[0]||base.buddy||'🐾',color:buddyColours[index%buddyColours.length],dateOfBirth:row['Date of birth']||'',sex:row.Sex||'',records:0,glucose:null,status:'Waiting'};}
function normaliseHealthRecord(row){return {memberId:memberKey(row['Member ID']||row['Family member']),date:row['Date & time']||'',session:row.Session||'',glucose:row['Glucose (mmol/L)'],bloodPressure:row['Blood pressure (mmHg)'],pulse:row['Pulse (bpm)'],temperature:row['Temperature (°C)'],weight:row['Weight (kg)'],height:row['Height (cm)'],notes:row.Notes||''};}
function recordDate(record){const value=new Date(record.date);return Number.isNaN(value.getTime())?0:value.getTime();}
function weeklyRecords(memberId){const start=Date.now()-6*86400000;return healthRecords.filter(r=>r.memberId===memberId&&recordDate(r)>=start);}
function latestRecord(memberId){return healthRecords.filter(r=>r.memberId===memberId).sort((a,b)=>recordDate(b)-recordDate(a))[0];}
function applyHealthToFamily(){family=family.map(m=>{const latest=latestRecord(m.id), weekly=weeklyRecords(m.id);return {...m,records:weekly.length,glucose:latest&&latest.glucose!==''?Number(latest.glucose):null,status:latest?'Checked in':'Waiting',latest};});}
function renderToday() { if(!healthRecords.length){document.querySelector('#todayCards').innerHTML='<div class="appointment-empty">No health check-ins yet 🌱</div>';return;} document.querySelector('#todayCards').innerHTML=family.map(m=>{const ref=getGlucoseReference(m.glucose);return `<article class="member-card"><div class="buddy" style="--buddy-bg:${m.color}">${m.buddy}</div><span class="check-state ${m.status==='Waiting'?'waiting':''}">${m.status==='Waiting'?'⌛ ':'✓ '}${m.status==='Waiting'?'No check-in yet':'Checked in'}</span><h3>${m.name}</h3><p>${m.role}</p><div class="mini-stat">${m.glucose!==null?`<span class="glucose-result ${ref?.key||'normal'}" title="${ref?.label||'Glucose'} colour on reference card"><strong>${m.glucose}</strong><span>mmol/L glucose</span><em>${ref?.label||'Glucose'}</em></span>`:'Latest reading —'}</div></article>`}).join(''); }
function renderFamily() { document.querySelector('#familyCards').innerHTML=family.map(m=>{const next=appointments.filter(a=>a.memberId===m.id&&(a.status==='Upcoming'||a.status==='Rescheduled')).sort((a,b)=>(a.date||'').localeCompare(b.date||''))[0];return `<article class="family-card" data-family-card="${m.id}"><button class="edit-profile" data-edit-member="${m.id}" type="button">Edit profile</button><div class="big-buddy" style="--buddy-bg:${m.color}">${m.buddy}</div><div><p class="eyebrow">${m.role}</p><h2>${m.name}</h2><p>${m.latest?'Latest check-in from your family health record.':'No health check-ins yet 🌱'}</p><div class="family-stats"><span><strong>${m.records}</strong> weekly logs</span><span><strong>${m.glucose??'—'}</strong> latest glucose</span></div>${next?`<p class="family-upcoming">${appointmentIcons[next.appointmentType]||'📅'} Next: ${next.appointmentType} · ${formatAppointmentDate(next.date)}</p>`:''}</div></article>`}).join('')||'<div class="appointment-empty">No family profiles found in Google Sheets.</div>'; }
function jsonp(action,data={}) { return new Promise((resolve,reject)=>{const callback=`healthBuddies_${Date.now()}_${Math.random().toString(36).slice(2)}`,url=new URL(SCRIPT_URL),script=document.createElement('script'),timer=setTimeout(()=>done(new Error('Google Sheet request timed out.')),15000);let finished=false;Object.entries({action,callback,...data}).forEach(([key,value])=>url.searchParams.set(key,value??''));function done(error,result){if(finished)return;finished=true;clearTimeout(timer);delete window[callback];script.remove();error?reject(error):resolve(result);}window[callback]=result=>done(null,result);script.onerror=()=>done(new Error('Google Sheet request was blocked.'));script.src=url.toString();document.head.appendChild(script);}); }
function formPost(action,data={}) { return new Promise((resolve,reject)=>{const frameName=`healthBuddiesPost_${Date.now()}`,frame=document.createElement('iframe'),form=document.createElement('form'),timer=setTimeout(()=>finish(new Error('Google Sheet save timed out.')),15000);let finished=false;frame.name=frameName;frame.hidden=true;form.hidden=true;form.method='POST';form.action=SCRIPT_URL;form.target=frameName;Object.entries({action,...data}).forEach(([key,value])=>{const input=document.createElement('input');input.type='hidden';input.name=key;input.value=value??'';form.appendChild(input);});function finish(error){if(finished)return;finished=true;clearTimeout(timer);form.remove();frame.remove();error?reject(error):resolve({ok:true});}frame.onload=()=>finish();document.body.append(frame,form);form.submit();}); }
function api(action,data={},method='POST') { if(!SCRIPT_URL) return Promise.reject(new Error('Connect your private Apps Script URL first.')); if(method==='GET'){const url=new URL(SCRIPT_URL);url.searchParams.set('action',action);return fetch(url).then(r=>r.json()).catch(()=>jsonp(action,data));} return fetch(SCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,...data})}).then(r=>r.json()).catch(()=>formPost(action,data)); }
function dbMemberId(member){return member.dbId||member.id;}
function normaliseAppointment(row){return {id:row.Appointment_ID||row.id,memberId:memberKey(row.Family_Member_ID||row.memberId||''),memberName:row.Family_Member_Name||row.memberName,appointmentType:row.Appointment_Type||row.appointmentType,title:row.Title||row.title,date:row.Date||row.date,time:row.Time||row.time,providerName:row.Provider_Name||row.providerName,clinicHospital:row.Clinic_Hospital||row.clinicHospital,location:row.Location||row.location,purpose:row.Purpose||row.purpose,status:row.Status||row.status||'Upcoming',notes:row.Notes||row.notes,childFeeling:row.Child_Feeling||row.childFeeling};}
function formatAppointmentDate(date){if(!date)return 'Date to be confirmed';const value=new Date(`${date}T00:00:00`);return Number.isNaN(value)?date:value.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});}
function renderAppointmentCard(a,compact=false){const member=family.find(m=>m.id===a.memberId)||{name:a.memberName||'Family member',buddy:'🐾'};const status=a.status||'Upcoming';return `<article class="appointment-card" data-appointment="${a.id}"><div class="appointment-type-icon">${appointmentIcons[a.appointmentType]||'📅'}</div><div><h3>${a.title||a.appointmentType||'Appointment'}</h3><p>${member.buddy} ${member.name} · ${formatAppointmentDate(a.date)}${a.time?` · ${a.time}`:''}</p><small>${a.clinicHospital||a.providerName||'Details to be confirmed'}</small></div><span class="appointment-status ${status.toLowerCase()}">${status==='Completed'?'✓ ':''}${status}</span>${compact?'':`<div class="appointment-actions"><button class="small-btn" data-appointment-action="edit">View / edit</button>${status!=='Completed'&&status!=='Cancelled'?'<button class="small-btn" data-appointment-action="complete">Mark completed</button>':''}<button class="small-btn danger" data-appointment-action="delete">Delete</button></div>`}</article>`;}
function renderAppointments(){const upcoming=appointments.filter(a=>a.status==='Upcoming'||a.status==='Rescheduled').sort((a,b)=>(a.date||'').localeCompare(b.date||''));const recent=appointments.filter(a=>a.status==='Completed'||a.status==='Cancelled').sort((a,b)=>(b.date||'').localeCompare(a.date||''));const empty='<div class="appointment-empty">Nothing coming up — enjoy your day! 🌿</div>';document.querySelector('#upcomingAppointments').innerHTML=upcoming.length?upcoming.map(a=>renderAppointmentCard(a)).join(''):empty;document.querySelector('#recentAppointments').innerHTML=recent.length?recent.map(a=>renderAppointmentCard(a)).join(''):'<div class="appointment-empty">No recent visits yet.</div>';document.querySelector('#dashboardAppointments').innerHTML=upcoming.length?upcoming.slice(0,2).map(a=>renderAppointmentCard(a,true)).join(''):empty;renderFamily();}
async function loadAppointments(){try{const result=await api('getAppointments',{},'GET');if(!result.ok)throw new Error(result.error);appointments=(result.data||[]).map(normaliseAppointment);renderAppointments();}catch{appointments=[];renderAppointments();}}
function renderMemberPicker() {
  document.querySelector('#memberPicker').innerHTML = family.map(m => `<button type="button" class="member-choice ${m.id===selectedMember?'active':''}" data-member="${m.id}"><span>${m.buddy}</span>${m.name}</button>`).join('');
}
function renderInputs() {
  const picked = [...document.querySelectorAll('input[name="metric"]:checked')].map(el => el.value);
  document.querySelector('#valueInputs').innerHTML = picked.map(key => { const [name, unit, example] = labels[key]; return `<div class="input-group"><label for="${key}">${name} <span>(${unit})</span></label><input id="${key}" name="${key}" required placeholder="${example}" inputmode="decimal"></div>`; }).join('');
  renderReferenceGuides();
}
function getFormReadings() { const bp=(document.querySelector('#bloodPressure')?.value || '').match(/(\d{2,3})\s*\/?\s*(\d{2,3})/); return {glucose:document.querySelector('#glucose')?.value, systolicBp:bp?Number(bp[1]):null, diastolicBp:bp?Number(bp[2]):null, pulseBpm:Number(document.querySelector('#pulse')?.value)||null, temperatureC:Number(document.querySelector('#temperature')?.value)||null, weightKg:Number(document.querySelector('#weight')?.value)||null, heightCm:Number(document.querySelector('#height')?.value)||null}; }
function statusTone(text='') { const value=text.toLowerCase(); return value.includes('typical')||value.includes('within')||value.includes('healthy')?'status-good':value.includes('elevated')||value.includes('above typical')?'status-caution':value.includes('stage')||value.includes('fever')||value.includes('severe')?'status-review':'status-caution'; }
function liveLine(title,value,status,tone='') { return `<div class="guide-live ${tone}"><strong>${title}${value?` · ${value}`:''}</strong><span>${status}</span></div>`; }
function renderReferenceGuides() { const picked=[...document.querySelectorAll('input[name="metric"]:checked')].map(el=>el.value); const holder=document.querySelector('#referenceGuides'); const member=family.find(m=>m.id===selectedMember); const group=ageGroup(member.dateOfBirth); const v=getFormReadings(); const ref=getHealthReference({dateOfBirth:member.dateOfBirth,sex:member.sex,...v}); const guides=[];
  if(picked.includes('glucose')) { const tier=getGlucoseReference(v.glucose); guides.push(`<section class="health-guide glucose-guide"><div class="guide-top"><div><h2>Glucose colour guide</h2><p>Supplied indicator card · mmol/L</p></div><span class="guide-icon">🎨</span></div><div class="glucose-scale"><div class="guide-band low"><strong>Low</strong><span>≤ 3.9</span></div><div class="guide-band normal"><strong>Normal</strong><span>4.0–7.0</span></div><div class="guide-band borderline"><strong>Borderline</strong><span>7.1–10.0</span></div><div class="guide-band high"><strong>High</strong><span>10.1–13.8</span></div><div class="guide-band dangerous"><strong>Dangerous</strong><span>≥ 13.9</span></div></div>${tier?liveLine('Glucose',`${v.glucose} mmol/L · ${tier.label} colour band`,group==='Adult'?'Reference status only — not a medical diagnosis.':'Colour reference only — follow this child’s individual care plan.',tier.key):liveLine('Enter a glucose reading','', 'The matching colour and status will appear here.')}</section>`); }
  if(picked.includes('bloodPressure')) { const isAdult=group==='Adult'||group==='Adolescent'; const status=v.systolicBp?ref.bpCategory:null; guides.push(`<section class="health-guide"><div class="guide-top"><div><h2>Blood pressure</h2><p>${isAdult?'Adult/adolescent reference guide':'Child reference guide'}</p></div><span class="guide-icon">♥</span></div>${isAdult?'<div class="guide-chip-row"><span class="status-chip bp-normal">🟢 Normal · &lt;120 / &lt;80</span><span class="status-chip bp-elevated">🟡 Elevated · 120–129 / &lt;80</span><span class="status-chip bp-stage1">🟠 Stage 1 · 130–139 or 80–89</span><span class="status-chip bp-stage2">🔴 Stage 2 · ≥140 or ≥90</span></div>':'<p class="guide-note">Child BP uses age-, sex- and height-specific references. No adult thresholds are displayed.</p>'}${status?liveLine('Blood pressure',`${v.systolicBp}/${v.diastolicBp} mmHg`,status,statusTone(status)):liveLine('Enter blood pressure','',isAdult?'Reference status only — not a medical diagnosis.':'A validated pediatric dataset is required for a final reference status.')}</section>`); }
  if(picked.includes('pulse')) { const status=v.pulseBpm?ref.pulseCategory:null; guides.push(`<section class="health-guide"><div class="guide-top"><div><h2>Pulse</h2><p>${group==='Adult'?'Typical resting reference: 60–100 bpm':'Age-specific pediatric reference'}</p></div><span class="guide-icon">♡</span></div>${status?liveLine('Pulse',`${v.pulseBpm} bpm`,status,statusTone(status)):liveLine('Enter a pulse','',group==='Adult'?'Context matters — a single reading is not a diagnosis.':'Age-specific pediatric reference required.')}</section>`); }
  if(picked.includes('temperature')) { const status=v.temperatureC?ref.temperatureCategory:null; guides.push(`<section class="health-guide"><div class="guide-top"><div><h2>Temperature</h2><p>Typical range 36.1–37.2°C · method and age matter</p></div><span class="guide-icon">🌡</span></div>${status?liveLine('Temperature',`${v.temperatureC}°C`,status,statusTone(status)):liveLine('Enter a temperature','', '38.0°C or higher shows a fever reference flag; this is not a diagnosis.')}</section>`); }
  if(picked.includes('weight')&&picked.includes('height')) { const status=ref.bmiCategory; guides.push(`<section class="health-guide"><div class="guide-top"><div><h2>BMI / growth</h2><p>${group==='Adult'?'Calculated from weight and height':'Age- and sex-specific growth reference'}</p></div><span class="guide-icon">⚖</span></div>${ref.bmi?liveLine('BMI',`${ref.bmi.toFixed(1)} kg/m²`,status,statusTone(status)):liveLine('Enter weight and height','',group==='Adult'?'BMI will be calculated automatically.':'A validated child growth reference is required for a percentile/category.')}</section>`); }
  holder.innerHTML=guides.join('');
}
function renderChart(){const chart=document.querySelector('#trendChart'),key=document.querySelector('#chartKey');if(!chart||!key)return;const colours={mommy:'#f065b8',daddy:'#92d91f',qaayed:'#3d7fff',qarizh:'#18b86d'},days=selectedRange==='week'?7:30,now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-(days-1));const series=family.map(member=>{const points=healthRecords.filter(record=>record.memberId===member.id&&Number.isFinite(Number(record.glucose))).map(record=>({time:recordDate(record),value:Number(record.glucose)})).filter(point=>point.time>=start.getTime()).sort((a,b)=>a.time-b.time);return {...member,points,colour:colours[member.id]||'#5da89e'};}).filter(member=>member.points.length);if(!series.length){chart.innerHTML='<div class="appointment-empty">No glucose trend yet — record a real glucose check-in to start the chart.</div>';key.innerHTML='';return;}const values=series.flatMap(member=>member.points.map(point=>point.value)),min=Math.floor(Math.min(...values)-1),max=Math.ceil(Math.max(...values)+1),range=Math.max(1,max-min),w=720,h=190,left=42,right=14,top=12,bottom=35,x=time=>left+((time-start.getTime())/(now.getTime()-start.getTime()||1))*(w-left-right),y=value=>top+((max-value)/range)*(h-top-bottom);const grid=Array.from({length:5},(_,i)=>{const value=min+(range/4)*i;return `<line x1="${left}" x2="${w-right}" y1="${y(value)}" y2="${y(value)}" class="trend-grid"/><text x="5" y="${y(value)+4}" class="trend-axis">${value.toFixed(1).replace('.0','')}</text>`}).join('');const paths=series.map(member=>{const path=member.points.map(point=>`${x(point.time)},${y(point.value)}`).join(' ');const dots=member.points.map(point=>`<circle cx="${x(point.time)}" cy="${y(point.value)}" r="3.7" fill="#fff" stroke="${member.colour}" stroke-width="2.4"><title>${member.name}: ${point.value.toFixed(1)} mmol/L</title></circle>`).join('');return `<polyline points="${path}" fill="none" stroke="${member.colour}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${dots}`}).join('');chart.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Family glucose trends">${grid}${paths}<text x="${left}" y="${h-8}" class="trend-axis">${start.toLocaleDateString(undefined,{day:'numeric',month:'short'})}</text><text x="${w-right}" y="${h-8}" text-anchor="end" class="trend-axis">${now.toLocaleDateString(undefined,{day:'numeric',month:'short'})}</text></svg>`;key.innerHTML=series.map(member=>`<span><i class="dot" style="background:${member.colour}"></i>${member.name}</span>`).join('');}
function renderAchievement(){const weekly=healthRecords.filter(r=>recordDate(r)>=Date.now()-6*86400000).length;document.querySelector('#achievementTitle').textContent=weekly?'Healthy habit heroes!':'No health check-ins yet 🌱';document.querySelector('#achievementText').textContent=weekly?'Your real family check-ins are shown below.':'Your family’s real check-ins will appear here.';document.querySelector('#achievementProgress').style.width=`${Math.min(100,weekly/24*100)}%`;document.querySelector('#achievementCount').textContent=`${weekly} weekly check-in${weekly===1?'':'s'}`;}
async function loadLiveData(){let profileResult,recordResult,appointmentResult;try{[profileResult,recordResult,appointmentResult]=await Promise.all([api('getFamilyProfiles',{},'GET'),api('getHealthRecords',{},'GET'),api('getAppointments',{},'GET')]);if(profileResult.ok&&(profileResult.data||[]).length)family=(profileResult.data||[]).map(normaliseProfile);if(recordResult.ok)healthRecords=(recordResult.data||[]).map(normaliseHealthRecord);if(appointmentResult.ok)appointments=(appointmentResult.data||[]).map(normaliseAppointment);}catch(error){toast('Could not refresh Google Sheet data. Showing family profiles with no invented readings.');}applyHealthToFamily();if(!family.some(member=>member.id===selectedMember))selectedMember=family[0].id;renderToday();renderFamily();renderMemberPicker();renderInputs();renderChart();renderAchievement();renderAppointments();}
function activatePage(page) { document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page)); document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page)); if(page==='appointments'){const member=family.find(m=>m.id===selectedMember);document.querySelector('#appointmentBuddy').textContent=member.buddy;loadAppointments();} window.scrollTo({top:0,behavior:'smooth'}); }
function toast(msg) { const t=document.querySelector('#toast'); t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200); }
function saveFamily() { /* Family profiles are read from Google Sheets; no browser-stored profile data is used. */ }
function buddyEmoji(label) { return label.trim().split(' ')[0]; }
function buddyMessage(member) { return ({mommy:"Let's check in, Mommy! 💚",daddy:'Ready for your check-in? 💙',qaayed:'Nice job checking in! ⭐',qarizh:"Let's see how you're doing! 🐾"})[member.id] || `Let’s check in, ${member.name}!`; }
function reactBuddy(message) { const buddy=document.querySelector('#recordBuddy'); buddy.classList.remove('react'); void buddy.offsetWidth; buddy.classList.add('react'); document.querySelector('#buddyMessage').textContent=message; }
function summaryItem(icon,label,value,status,tone='status-caution') { return `<article class="summary-item"><span class="summary-icon">${icon}</span><div><strong>${label}</strong><span>${value}</span></div><span class="summary-status ${tone}">${status}</span></article>`; }
function openSuccess(member,values,reference,picked) { const glucose=getGlucoseReference(values.glucose); const list=[]; if(picked.includes('glucose')&&values.glucose) list.push(summaryItem('🩸','Glucose',`${values.glucose} mmol/L`,glucose.label,glucose.key)); if(picked.includes('bloodPressure')&&values.systolicBp) list.push(summaryItem('♥','Blood pressure',`${values.systolicBp}/${values.diastolicBp} mmHg`,reference.bpCategory,statusTone(reference.bpCategory))); if(picked.includes('pulse')&&values.pulseBpm) list.push(summaryItem('♡','Pulse',`${values.pulseBpm} bpm`,reference.pulseCategory,statusTone(reference.pulseCategory))); if(picked.includes('temperature')&&values.temperatureC) list.push(summaryItem('🌡','Temperature',`${values.temperatureC}°C`,reference.temperatureCategory,statusTone(reference.temperatureCategory))); if(picked.includes('weight')&&values.weightKg) list.push(summaryItem('⚖','Weight',`${values.weightKg} kg`,'Recorded','status-good')); if(picked.includes('height')&&values.heightCm) list.push(summaryItem('↕','Height',`${values.heightCm} cm`,'Recorded','status-good')); if(picked.includes('weight')&&picked.includes('height')&&reference.bmi) list.push(summaryItem('◌','BMI',`${reference.bmi.toFixed(1)} kg/m²`,reference.bmiCategory,statusTone(reference.bmiCategory))); document.querySelector('#successBuddy').textContent=member.buddy;document.querySelector('#successTitle').textContent='Check-in saved! 💚';document.querySelector('#successMessage').textContent=`${buddyMessage(member)} Nice job keeping track of your health.`;document.querySelector('#successSummary').innerHTML=list.join('');const modal=document.querySelector('#successModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false'); }
function closeSuccess() { const modal=document.querySelector('#successModal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true'); }
function openProfile(member) { const next=appointments.filter(a=>a.memberId===member.id&&(a.status==='Upcoming'||a.status==='Rescheduled')).sort((a,b)=>(a.date||'').localeCompare(b.date||''))[0];const completed=appointments.filter(a=>a.memberId===member.id&&a.status==='Completed').length;document.querySelector('#editMemberId').value=member.id;document.querySelector('#editName').value=member.name;document.querySelector('#editRole').value=member.role;document.querySelector('#editDob').value=member.dateOfBirth || '';document.querySelector('#editSex').value=member.sex || '';document.querySelector('#editBuddy').value=[...document.querySelector('#editBuddy').options].find(o=>o.value.startsWith(member.buddy))?.value || '🐼 Panda';document.querySelector('#profileSummary').innerHTML=`<strong>${member.buddy} ${member.name}'s little summary</strong><span>Age ${ageYears(member.dateOfBirth)??'not set'} · ${member.records}/6 recent check-ins${member.glucose?` · latest glucose ${member.glucose} mmol/L`:''}</span><span>${next?`${appointmentIcons[next.appointmentType]||'📅'} Next: ${next.appointmentType} · ${formatAppointmentDate(next.date)}`:completed?`✓ ${completed} completed visit${completed===1?'':'s'} recorded.`:'No appointment recorded yet.'}</span>`;document.querySelector('#profileModal').classList.add('open');document.querySelector('#profileModal').setAttribute('aria-hidden','false'); }
function closeProfile() { document.querySelector('#profileModal').classList.remove('open');document.querySelector('#profileModal').setAttribute('aria-hidden','true'); }
function openAppointment(appointment=null){const isEdit=Boolean(appointment);document.querySelector('#appointmentTitle').textContent=isEdit?'Edit appointment':'Add an appointment';document.querySelector('#appointmentId').value=appointment?.id||'';document.querySelector('#appointmentMember').innerHTML=family.map(m=>`<option value="${m.id}" ${(appointment?.memberId||selectedMember)===m.id?'selected':''}>${m.buddy} ${m.name}</option>`).join('');document.querySelector('#appointmentType').value=appointment?.appointmentType||'Dentist';document.querySelector('#appointmentName').value=appointment?.title||'';document.querySelector('#appointmentStatus').value=appointment?.status||'Upcoming';document.querySelector('#appointmentDate').value=appointment?.date||'';document.querySelector('#appointmentTime').value=appointment?.time||'';document.querySelector('#appointmentProvider').value=appointment?.providerName||'';document.querySelector('#appointmentClinic').value=appointment?.clinicHospital||'';document.querySelector('#appointmentLocation').value=appointment?.location||'';document.querySelector('#appointmentPurpose').value=appointment?.purpose||'';document.querySelector('#appointmentFeeling').value=appointment?.childFeeling||'';document.querySelector('#appointmentNotes').value=appointment?.notes||'';const modal=document.querySelector('#appointmentModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');}
function closeAppointment(){const modal=document.querySelector('#appointmentModal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}
function appointmentPayload(){const member=family.find(m=>m.id===document.querySelector('#appointmentMember').value);return {memberId:dbMemberId(member),memberName:member.name,appointmentType:document.querySelector('#appointmentType').value,title:document.querySelector('#appointmentName').value.trim(),status:document.querySelector('#appointmentStatus').value,date:document.querySelector('#appointmentDate').value,time:document.querySelector('#appointmentTime').value,providerName:document.querySelector('#appointmentProvider').value.trim(),clinicHospital:document.querySelector('#appointmentClinic').value.trim(),location:document.querySelector('#appointmentLocation').value.trim(),purpose:document.querySelector('#appointmentPurpose').value.trim(),childFeeling:document.querySelector('#appointmentFeeling').value,notes:document.querySelector('#appointmentNotes').value.trim()};}
function closeAppointmentSuccess(){const modal=document.querySelector('#appointmentSuccess');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}

document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>activatePage(b.dataset.page)));
document.querySelectorAll('.jump-record').forEach(b=>b.addEventListener('click',()=>activatePage('record')));
document.querySelectorAll('[data-page-jump]').forEach(b=>b.addEventListener('click',()=>activatePage(b.dataset.pageJump)));
document.querySelector('#profileQuick').addEventListener('click',()=>activatePage('family'));
document.querySelector('#familyCards').addEventListener('click',e=>{const button=e.target.closest('[data-edit-member]');if(button){openProfile(family.find(m=>m.id===button.dataset.editMember));return;}const card=e.target.closest('[data-family-card]');if(card){const member=family.find(m=>m.id===card.dataset.familyCard);openProfile(member);toast(`${member.name}'s family summary is ready to explore.`);}});
document.querySelector('#closeProfile').addEventListener('click',closeProfile);
document.querySelector('#profileModal').addEventListener('click',e=>{if(e.target.id==='profileModal')closeProfile();});
document.querySelector('#profileForm').addEventListener('submit',async e=>{e.preventDefault();const member=family.find(m=>m.id===document.querySelector('#editMemberId').value);const result=await api('updateFamilyProfile',{memberId:member.dbId,name:document.querySelector('#editName').value.trim(),relationship:document.querySelector('#editRole').value.trim(),buddyAnimal:document.querySelector('#editBuddy').value.replace(/^\S+\s*/,''),dateOfBirth:document.querySelector('#editDob').value,sex:document.querySelector('#editSex').value});if(!result.ok){toast(result.error||'Could not update the Google Sheet profile.');return;}closeProfile();await loadLiveData();toast('Family profile saved to Google Sheets.');});
document.querySelector('#memberPicker').addEventListener('click',e=>{const b=e.target.closest('[data-member]');if(!b)return;selectedMember=b.dataset.member;const member=family.find(m=>m.id===selectedMember);renderMemberPicker();document.querySelector('#recordBuddy').textContent=member.buddy;reactBuddy(buddyMessage(member));renderReferenceGuides();});
document.querySelector('#sessionPicker').addEventListener('click',e=>{const b=e.target.closest('[data-session]');if(!b)return;selectedSession=b.dataset.session;document.querySelectorAll('.session-pill').forEach(x=>x.classList.toggle('active',x===b));reactBuddy('Perfect timing — we’re ready when you are! ✨');});
document.querySelector('.measure-grid').addEventListener('change',e=>{const card=e.target.closest('.measure-card');card.classList.toggle('selected',e.target.checked);renderInputs();reactBuddy('Great choice — let’s record it together! ✨');});
document.querySelector('#valueInputs').addEventListener('input',renderReferenceGuides);
document.querySelector('#selectAll').addEventListener('click',()=>{document.querySelectorAll('input[name="metric"]').forEach(x=>{x.checked=true;x.closest('.measure-card').classList.add('selected')});renderInputs();});
document.querySelectorAll('.range-btn').forEach(b=>b.addEventListener('click',()=>{selectedRange=b.dataset.range;document.querySelectorAll('.range-btn').forEach(x=>x.classList.toggle('active',x===b));renderChart();}));
document.querySelector('#healthForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const saveButton=form.querySelector('.save-btn');const oldLabel=saveButton.innerHTML;const member=family.find(m=>m.id===selectedMember);const picked=[...document.querySelectorAll('input[name="metric"]:checked')].map(el=>el.value);const values=getFormReadings();const reference=getHealthReference({dateOfBirth:member.dateOfBirth,sex:member.sex,...values});const payload={memberId:dbMemberId(member),memberName:member.name,session:selectedSession,notes:document.querySelector('#notes').value};document.querySelectorAll('#valueInputs input').forEach(i=>payload[i.name]=i.value);saveButton.classList.add('saving');saveButton.disabled=true;saveButton.innerHTML='Saving your check-in… ✨';try{const result=await api('createHealthRecord',payload);if(!result.ok)throw new Error(result.error);await loadLiveData();const savedMember=family.find(m=>m.id===selectedMember);reactBuddy('Yay! Your check-in is saved! ✨');openSuccess(savedMember,values,reference,picked);form.reset();document.querySelector('input[name="metric"][value="glucose"]').checked=true;document.querySelectorAll('.measure-card').forEach(c=>c.classList.toggle('selected',c.querySelector('input').value==='glucose'));renderInputs();}catch(error){toast(error.message||'Your health check-in could not be saved. Please check the Sheets connection.');}finally{saveButton.classList.remove('saving');saveButton.disabled=false;saveButton.innerHTML=oldLabel;}});
document.querySelector('#doneSuccess').addEventListener('click',closeSuccess);
document.querySelector('#successModal').addEventListener('click',e=>{if(e.target.id==='successModal')closeSuccess();});
document.querySelector('#addAppointment').addEventListener('click',()=>openAppointment());
document.querySelector('#closeAppointment').addEventListener('click',closeAppointment);
document.querySelector('#appointmentModal').addEventListener('click',e=>{if(e.target.id==='appointmentModal')closeAppointment();});
document.querySelector('#appointmentForm').addEventListener('submit',async e=>{e.preventDefault();const button=document.querySelector('#saveAppointment');const old=button.innerHTML;const appointmentId=document.querySelector('#appointmentId').value;button.disabled=true;button.classList.add('saving');button.textContent='Saving appointment…';try{const result=await api(appointmentId?'updateAppointment':'createAppointment',Object.assign(appointmentPayload(),appointmentId?{appointmentId}:{ }));if(!result.ok)throw new Error(result.error);closeAppointment();await loadAppointments();toast('Appointment saved! Your buddy is coming along. ✨');}catch(error){toast(error.message||'We could not save the appointment. Please check the Sheets connection.');}finally{button.disabled=false;button.classList.remove('saving');button.innerHTML=old;}});
document.querySelector('#upcomingAppointments').addEventListener('click',async e=>{const card=e.target.closest('[data-appointment]');const action=e.target.closest('[data-appointment-action]')?.dataset.appointmentAction;if(!card||!action)return;const appointment=appointments.find(a=>a.id===card.dataset.appointment);if(action==='edit')openAppointment(appointment);if(action==='delete'){if(!confirm('Delete this appointment?'))return;try{const result=await api('deleteAppointment',{appointmentId:appointment.id});if(!result.ok)throw new Error(result.error);await loadAppointments();toast('Appointment removed.');}catch(error){toast(error.message||'Could not remove the appointment.');}}if(action==='complete'){try{const result=await api('completeAppointment',{appointmentId:appointment.id});if(!result.ok)throw new Error(result.error);await loadAppointments();const member=family.find(m=>m.id===appointment.memberId)||{buddy:'🐾',name:appointment.memberName};document.querySelector('#appointmentSuccessBuddy').textContent=member.buddy;document.querySelector('#appointmentSuccessText').textContent=`Well done, ${member.name}! You did a brave thing today. ⭐`;document.querySelector('#appointmentSuccessInfo').innerHTML=summaryItem(appointmentIcons[appointment.appointmentType]||'📅',appointment.appointmentType,formatAppointmentDate(appointment.date),'Completed','status-good');document.querySelector('#appointmentSuccess').classList.add('open');document.querySelector('#appointmentSuccess').setAttribute('aria-hidden','false');}catch(error){toast(error.message||'Could not complete the appointment.');}}});
document.querySelector('#doneAppointment').addEventListener('click',closeAppointmentSuccess);
document.querySelector('#appointmentSuccess').addEventListener('click',e=>{if(e.target.id==='appointmentSuccess')closeAppointmentSuccess();});
document.querySelector('#dashboardAppointments').addEventListener('click',e=>{const card=e.target.closest('[data-appointment]');if(card){activatePage('appointments');const appointment=appointments.find(a=>a.id===card.dataset.appointment);if(appointment)openAppointment(appointment);}});
renderAchievement();loadLiveData();
