/* Health Buddies bound Apps Script — deploy this single project as a Web App. */
const HEALTH_SHEET = 'Health Records';
const APPOINTMENTS_SHEET = 'Appointments';
const APPOINTMENT_HEADERS = ['Appointment_ID','Family_Member_ID','Family_Member_Name','Appointment_Type','Title','Date','Time','Provider_Name','Clinic_Hospital','Location','Purpose','Status','Notes','Next_Appointment_Date','Child_Feeling','Pre_Visit_Note','Post_Visit_Note','Created_At','Updated_At'];

function json(data, callback) { const body=JSON.stringify(data); return ContentService.createTextOutput(callback?`${callback}(${body});`:body).setMimeType(callback?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON); }
function getSheet(name) { const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(name); if (!sheet) throw new Error(`Missing required sheet: ${name}`); return sheet; }
function dateValue(value, key) { if (!(value instanceof Date)) return value; const zone=Session.getScriptTimeZone(); if (key==='Time') return Utilities.formatDate(value,zone,'HH:mm'); return Utilities.formatDate(value,zone,key==='Date & time'||key==='Created_At'||key==='Updated_At'?'yyyy-MM-dd HH:mm:ss':'yyyy-MM-dd'); }
function appointmentEntries() { const sheet=getSheet(APPOINTMENTS_SHEET), values=sheet.getDataRange().getValues(), headerIndex=values.findIndex(row=>row[0]==='Appointment_ID'); if(headerIndex<0) throw new Error('Appointments headers were not found.'); const headers=values[headerIndex], headerRow=headerIndex+1; const entries=values.slice(headerIndex+1).map((row,index)=>({rowNumber:headerRow+index+1,record:headers.reduce((obj,key,i)=>{obj[key]=dateValue(row[i],key);return obj;},{})})).filter(entry=>entry.record.Appointment_ID); return {sheet,entries}; }
function writeHealthRecord(data) { const sheet=getSheet(HEALTH_SHEET); sheet.appendRow([new Date(),data.memberId||'',data.memberName||'',data.session||'',data.glucose||'',data.bloodPressure||'',data.pulse||'',data.temperature||'',data.weight||'',data.height||'',data.notes||'','Web app']); return {ok:true}; }
function tableEntries(sheetName, firstHeader) { const sheet=getSheet(sheetName), values=sheet.getDataRange().getValues(), headerIndex=values.findIndex(row=>row[0]===firstHeader); if(headerIndex<0) throw new Error(`${sheetName} headers were not found.`); const headers=values[headerIndex]; return values.slice(headerIndex+1).map(row=>headers.reduce((record,key,index)=>{record[key]=dateValue(row[index],key);return record;},{})).filter(record=>record[firstHeader]); }
function getHealthRecords() { return tableEntries(HEALTH_SHEET,'Date & time'); }
function getFamilyProfiles() { return tableEntries('Family Profiles','Member ID'); }
function profileEntries() { const sheet=getSheet('Family Profiles'), values=sheet.getDataRange().getValues(), headerIndex=values.findIndex(row=>row[0]==='Member ID'); if(headerIndex<0) throw new Error('Family Profiles headers were not found.'); const headers=values[headerIndex], headerRow=headerIndex+1; return {sheet,headers,entries:values.slice(headerIndex+1).map((row,index)=>({rowNumber:headerRow+index+1,record:headers.reduce((record,key,column)=>{record[key]=dateValue(row[column],key);return record;},{})})).filter(entry=>entry.record['Member ID'])}; }
function updateFamilyProfile(data) { const set=profileEntries(), entry=set.entries.find(item=>String(item.record['Member ID'])===String(data.memberId)); if(!entry) throw new Error('Family member not found.'); const changes={'Name':data.name,'Buddy animal':data.buddyAnimal,'Relationship':data.relationship,'Date of birth':data.dateOfBirth,'Sex':data.sex}; const row=set.headers.map(header=>Object.prototype.hasOwnProperty.call(changes,header)?changes[header]:entry.record[header]); set.sheet.getRange(entry.rowNumber,1,1,set.headers.length).setValues([row]); return row.reduce((record,value,index)=>{record[set.headers[index]]=value;return record;},{}); }
function appointmentRow(data, existing) { const now=new Date(); const record={Appointment_ID:existing?.Appointment_ID||`APT-${Utilities.getUuid().slice(0,8).toUpperCase()}`,Family_Member_ID:data.memberId||existing?.Family_Member_ID||'',Family_Member_Name:data.memberName||existing?.Family_Member_Name||'',Appointment_Type:data.appointmentType||existing?.Appointment_Type||'',Title:data.title||existing?.Title||'',Date:data.date||existing?.Date||'',Time:data.time||existing?.Time||'',Provider_Name:data.providerName||existing?.Provider_Name||'',Clinic_Hospital:data.clinicHospital||existing?.Clinic_Hospital||'',Location:data.location||existing?.Location||'',Purpose:data.purpose||existing?.Purpose||'',Status:data.status||existing?.Status||'Upcoming',Notes:data.notes||existing?.Notes||'',Next_Appointment_Date:data.nextAppointmentDate||existing?.Next_Appointment_Date||'',Child_Feeling:data.childFeeling||existing?.Child_Feeling||'',Pre_Visit_Note:data.preVisitNote||existing?.Pre_Visit_Note||'',Post_Visit_Note:data.postVisitNote||existing?.Post_Visit_Note||'',Created_At:existing?.Created_At||now,Updated_At:now}; return record; }
function createAppointment(data) { const sheet=getSheet(APPOINTMENTS_SHEET); const record=appointmentRow(data); sheet.appendRow(APPOINTMENT_HEADERS.map(header=>record[header])); return record; }
function getAppointments() { return appointmentEntries().entries.map(entry=>entry.record); }
function getUpcomingAppointments() { const today=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd'); return getAppointments().filter(a=>a.Status==='Upcoming'||a.Status==='Rescheduled').filter(a=>!a.Date||a.Date>=today).sort((a,b)=>String(a.Date).localeCompare(String(b.Date))); }
function getFamilyMemberAppointments(memberId) { return getAppointments().filter(a=>a.Family_Member_ID===memberId); }
function updateAppointment(data) { const dataSet=appointmentEntries(), entry=dataSet.entries.find(item=>item.record.Appointment_ID===data.appointmentId); if(!entry) throw new Error('Appointment not found.'); const record=appointmentRow(data,entry.record); dataSet.sheet.getRange(entry.rowNumber,1,1,APPOINTMENT_HEADERS.length).setValues([APPOINTMENT_HEADERS.map(header=>record[header])]); return record; }
function deleteAppointment(data) { const dataSet=appointmentEntries(), entry=dataSet.entries.find(item=>item.record.Appointment_ID===data.appointmentId); if(!entry) throw new Error('Appointment not found.'); dataSet.sheet.deleteRow(entry.rowNumber); return {appointmentId:data.appointmentId}; }
function completeAppointment(data) { return updateAppointment(Object.assign({},data,{status:'Completed'})); }
function dispatch(data) { switch(data.action||'createHealthRecord'){case 'createHealthRecord':return writeHealthRecord(data);case 'getHealthRecords':return getHealthRecords();case 'getFamilyProfiles':return getFamilyProfiles();case 'updateFamilyProfile':return updateFamilyProfile(data);case 'createAppointment':return createAppointment(data);case 'getAppointments':return getAppointments();case 'getUpcomingAppointments':return getUpcomingAppointments();case 'getFamilyMemberAppointments':return getFamilyMemberAppointments(data.memberId);case 'updateAppointment':return updateAppointment(data);case 'deleteAppointment':return deleteAppointment(data);case 'completeAppointment':return completeAppointment(data);default:throw new Error('Unknown action.');} }
function doPost(e) { try { const raw=e&&e.postData&&e.postData.contents||''; const data=raw&&raw.charAt(0)==='{'?JSON.parse(raw):(e.parameter||{}); return json({ok:true,data:dispatch(data)}); } catch(error) { return json({ok:false,error:error.message}); } }
function doGet(e) { const callback=e&&e.parameter&&e.parameter.callback; try { return json({ok:true,data:dispatch(e.parameter||{})},callback); } catch(error) { return json({ok:false,error:error.message},callback); } }
